name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.2.2
  collection: ^1.18.0
  http_parser: ^4.0.0
  intl: ^0.19.0

  # Firebase dependencies
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.0

  # Downgrade leak_tracker to match with flutter_test's dependency
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: 3.0.5
  material_color_utilities: ^0.11.1
  string_scanner: ^1.2.0
  timezone: ^0.9.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gmail_logo.svg
    - assets/images/facebook_logo.svg
    - assets/images/linkedin_logo.svg
